/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package seno;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.fail;

import org.junit.jupiter.api.Test;

public class AppTest {

	@Test
	public void senoTest() throws Exception {
		Calculadora calculadora = new Calculadora();
		assertEquals(0.5, calculadora.seno(4, 8));
	}
}
