/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package seno;

import java.math.BigDecimal;

public class App {
    public static void main(String[] args) {
        try {
            Calculadora calculadora = new Calculadora();
            System.out.println(calculadora.seno(new BigDecimal(15), new BigDecimal(85)));
        }catch (Exception error) {
            error.printStackTrace();
        }
    }
}
